name: Sample Pipeline

on:
 push:
  branches: ["main"]
jobs:
   build:
     runs-on: [self-hosted,wsl-ubuntu]


     steps:
       - name: build step
         run:  echo "build pipeline"
   deploy:
   need: build
     runs-on: [self-hosted,wsl-ubuntu]

     steps:
       - name: Deploy step
         run:  echo "deploy pipeline"
     
